server:
  port: 8080 # 应用端口

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/hostpital_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # mapper 文件位置
  global-config:
    db-config:
      id-type: auto # 主键类型（全局自增）
  configuration:
    auto-mapping-behavior: partial # 只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true # 开启驼峰命名转换