server:
  port: 8080 # 应用端口

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/hostpital_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # mapper 文件位置
  global-config:
    db-config:
      id-type: auto # 主键类型（全局自增）
  configuration:
    auto-mapping-behavior: partial # 只对非嵌套的 ResultMap 进行自动映射
    map-underscore-to-camel-case: true # 开启驼峰命名转换

alipay:
  appId: 9021000134601207
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl/9xmzrP5a8+KeY6PW7yBWgrwswnDi4yBXbA+JHem7BkcZmTlO6gYBd71dd+Y/dfVUeJIfrbKlNrgidFQtB+8J7miYPihmvJ2cECFRIgRSVq/eh/v9SGnMh0TBbsoIZk9zzEQBFQEaV0Z+dSInn+DxUn0o5lqwjltKC/ZvzZJ/TtirFX7uggGFE4vrkfU6tCm6GL/oKpjOgRnxjprTIL2I4LReBaVNZSWblPPvqMzKNJqD4VfAic760uCJ3SZ5rcMTpgtCFOLue+rLRpgfZC99HFNwEnj6qabkYkPmJ6sNFSanU8jyBzZXhvue/X4sX3XIKTgBNr+NLcPNKqw4i/GwIDAQAB
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCDYiuxYdUuqkONMAiZ06lcTLIPMNjDSaGjQkLTDlLvW+crAwJTiKN60QLj8yBaLc7vCMUhGhScV0CqaVEDxeRGWYyNd7rDaY4R0ngcKFjGoHc5Fd5vjj1BedT8+fxwQRfTJyO5UUaWmgnOJWr4Wmk9h3UfJuza+/U/sBNA6wEktnoTNMnVkevZ0oPlOv2q2hM+MpjYFlgZftvZlvrcgUS1hx46P92c58a1xE1DRLL8EBEHvrDnhYpe69+3BodGse7IfDnDm2S//QSyjTtO61CB3v1zJ734DItNYw5loVt/vWCjI4p3mQaYgSzlxJagq9oV/7ZdXVjacYfR9IYjYphxAgMBAAECggEAIw11FM1CQEIC5c9T7B6Rh+Oaef0RSAEEE/egtoiSzfOaGFqkKz9ARosvFzwNfKHOHO4dEfjQWOnagdy5VaVdgvtvSWsRNAOceNrLWs/U56F2TY+tGdw8MZTco2Xa2OQ1BAvkNxQdHh8Y0JwhDwOoIldagyYyeTZRt101tdM9Kdr0FQQBvn10LFh5zlBJIOpybPnKRMVXFBLAacefjEwDzSFauptFSFdn8aWUDvpSbLC2RUXdZH9MA+ZrjJRbIBkOUbLAKELJU98g94zL5J7khQ4sEvIXCPl/2sV3Gkt9NDPZwIp3pAPL7fZiYN5a46AKUgfo3AwuHF/1GCUJx/ZcsQKBgQDvkhVfe5e+bQC5/IYeYw1/1qRa1bf/Vn2U0oFInpA2LoPlekLC0r9gQ1d4A5mhTB2o6BAGrRZC7jMlwrGU5ZvuHUMy/Kgej0MmQevtw+aRHvzj5vTt6qm5uJ8SsspX1RTFTzV0gV7PdWqFoT/F446vIc55+pSKY7iz8YKh4jY/dQKBgQCMZL82T0WOC3YPU12iSFjY7dOBe2IVGVxeDOWQ64D9/tVPJsT1I23lvHFnxNabG9IYJ3gpNJUxKxUAtwflF9VxnTIPNdQM+lPd2Ckx/zpvPdS+xV6iRMA7RXqtTITijY0gQ3Se0ek4tQqOCYxb7qGY91n4Fe69RFdEWSxzKqNxjQKBgQCRLaK8GSas5FtzWd9g3L/af5Vb4nW9S4mQvTxRaJ2V5/xP/RYmABavXD/OX8gi4gB7Uh4cHZoG91iRgnmg9L/YvWzyof+zfTfBIGO702KPAQtZhKVa5ED0Zjgn2acbMOqEY2rObnOpHsttrXj7D9pwsPjyHHMVpjbQ/QMf3Pjo3QKBgEd1qFYud0rbzpXyawCFLqQMOdH4SW5P4FIG4nqnRJsEMPL+2tWj2PZMurSE3m9I8+FThbgDicTjFuesQhp7zSrtRmOzlGGesT2EH0PRk563rCgGMisKL4Z70PuQrTrbre+0JhII6lrw25R8i7Lnfd1sWaELGN/Bf2HMufFMzLCpAoGBAKVpkRPA3GF6Z+dCQAba++oqq/Firmm3BXWCYM+UoOTn7bzPWre9tThnYhO+KkQrIhfq8m+2IuLpSJ5pQmrRp36fV+ogvrf5E511/zALDLeyqFkOfxmfYWtpYtLPdWXqqa/Uh+Fqr0gp37JUfd9+0QUfYyVLHUtJhKmNKKmoTgYD
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  returnUrl: alipay.trade.page.pay
  notifyUrl: alipay.trade.query

knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # API 文档语言
    language: en-US # zh-CN | en-US
    # API 文档 Footer 信息
    enableFooter: false # 是否显示 Footer 信息
    enableFooterCustom: true # 是否显示自定义 Footer 信息
    footerCustomContent: MIT | [JavGo](https://javgo.cn) # 自定义 Footer 内容
    # API 文档 Header 信息
    enableHomeCustom: true # 是否显示自定义 Header 信息
    homeCustomLocation: classpath:wiki/README.md # 自定义 Header 内容
    # API 文档 Models 信息
    enableSwaggerModels: true # 是否显示 Models 信息
    swaggerModelName: My Models # Models 名称

request:
  white-list: # 白名单
    adminPage: /page/admin/**
    userPage: /page/user/**
    doctorPage: /page/doctor/**
    loginPage: /page/login/login.html
    urls:
      - /admin/login
      - /user/login
      - /doctor/login
      - /user/register
      - /page/login/**
      - /page/index/**
      - /css/**
      - /img/**
      - /js/**
      - /plugins/**
      - /swagger/**
      - /doc.html